[#kubernetes-configuration-policy-controller]
= Kubernetes configuration policy controller

Configuration policy controller can be used to configure any Kubernetes resource and apply security policies across your
clusters. The configuration policy is provided in the `policy-templates` field of the policy on the hub and is
propagated to the selected managed clusters by the governance framework. See the
xref:../governance/policy_example.adoc#policy-yaml-structure[policy YAML documentation] for more about the hub policy.

The configuration policy controller communicates with the local Kubernetes API server to get the list of your
configurations that are in your cluster. For more information about CRDs, see
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/[Extend the
Kubernetes API with CustomResourceDefinitions].

The configuration policy controller is created on the managed cluster during installation. Configuration policy
controller supports the `enforce` feature to remediate when the configuration policy becomes NonCompliant. View the
following sample configuration policies:

|===
| Policy sample | Description

| https://github.com/stolostron/policy-collection/blob/main/stable/CM-Configuration-Management/policy-namespace.yaml[Namespace policy]
| Ensure consistent environment isolation and naming with Namespaces. See the Kubernetes
https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/[Namespace documentation].

| https://github.com/stolostron/policy-collection/blob/main/stable/CM-Configuration-Management/policy-pod.yaml[Pod policy]
| Ensure cluster workload configuration. See the Kubernetes https://kubernetes.io/docs/concepts/workloads/pods/[Pod documentation].

| https://github.com/stolostron/policy-collection/blob/main/stable/SC-System-and-Communications-Protection/policy-limitmemory.yaml[Memory usage policy]
| Limit workload resource usage using Limit Ranges. See the
https://kubernetes.io/docs/concepts/policy/limit-range/[Limit Range documentation].

| xref:../governance/psp_policy.adoc#pod-security-policy[Pod security policy]
| Ensure consistent workload security. See the Kubernetes
https://kubernetes.io/docs/concepts/policy/pod-security-policy/[Pod Security Policy documentation].

| xref:../governance/role_policy.adoc#role-policy[Role policy] +
xref:../governance/rolebinding_policy.adoc#role-binding-policy[Role binding policy]
| Manage role permissions and bindings using Roles and Role Bindings. See the Kubernetes https://kubernetes.io/docs/reference/access-authn-authz/rbac/[RBAC documentation].

| xref:../governance/scc_policy.adoc#security-context-constraints-policy[Security content constraints (SCC) policy]
| Manage workload permissions with Security Context Constraints. See the Openshift https://docs.openshift.com/container-platform/4.10/authentication/managing-security-context-constraints.html[Security Context Constraints documentation].

| xref:../governance/etcd_encryption_policy.adoc#etcd-encryption-policy[ETCD encryption policy]
| Ensure data security with etcd encryption. See the Openshift https://docs.openshift.com/container-platform/4.10/security/encrypting-etcd.html[etcd encryption documentation].

| xref:../governance/compliance_operator_policy.adoc#compliance-operator-policy[Compliance operator policy]
| 

| xref:../governance/image_vuln_policy.adoc#image-vulnerability-policy[Image vulnerability policy]
| 

| xref:../governance/gatekeeper_policy.adoc#gatekeeper-policy[Integrating gatekeeper constraints and constraint templates]
| 

|===

When the `remediationAction` for the configuration policy is set to `enforce`, the controller applies the specified
configuration to the target managed cluster. You can also use templated values inside of configuration policies. For
more information, see xref:../governance/custom_template.adoc#support-templates-in-config-policies[Support for templates
in configuration policies].

Continue reading to learn more about the configuration policy controller: 

* <<configuration-policy-sample,Configuration policy sample>>
* <<configuration-policy-yaml-table,Configuration policy YAML table>>

[#configuration-policy-sample]
== Configuration policy sample

[source,yaml]
----
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: policy-config
spec:
  namespaceSelector:
    include: ["default"]
    exclude: []
    matchExpressions: []
    matchLabels: {}
  remediationAction: inform
  severity: low
  object-templates:
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Pod
      metadata:
        name: pod
      spec:
        containers:
        - image: pod-image
          name: pod-name
          ports:
          - containerPort: 80
  evaluationInterval:
    compliant:
    noncompliant:
----

[#configuration-policy-yaml-table]
== Configuration policy YAML table

.Parameter table
|===
| Field | Description

| apiVersion
| Required.
Set the value to `policy.open-cluster-management.io/v1`.

| kind
| Required.
Set the value to `ConfigurationPolicy` to indicate the type of policy.

| metadata.name
| Required. The name of the policy.

| spec.namespaceSelector
| Required for namespaced objects that do not have a namespace specified. Determines namespaces in the managed cluster
that the object is applied to. The `include` and `exclude` parameters accept filepath expressions to include and exclude
namespaces by name. The `matchExpressions` and `matchLabels` parameters specify namespaces to include by label. (See the
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[Kubernetes labels and selectors]
documentation.) The resulting list is compiled by ANDing results from all parameters.

| spec.remediationAction
| Required. Specifies the action to take when the policy becomes NonCompliant. Use the following parameter values:
`inform` or `enforce`.

| spec.severity
| Required. Specifies the severity when the policy is non-compliant. Use the following parameter values: `low`,
`medium`, or `high`.

| spec.object-templates[].objectDefinition
| Required. The object definition for the controller to use to validate objects on the managed cluster.

| spec.object-templates[].complianceType
| Required. Behavior for Kubernetes objects that must be evaluated or applied to the managed clusters. You must use the
following verbs as parameter values:

`mustonlyhave`: Indicates that an object must exist with the exact fields and values as defined in the object.

`musthave`: Indicates an object must exist with the same fields as specified in the objectDefinition. The fields in the
template are a subset of what exists in the object. Array values are appended.

`mustnothave`: Indicates that an object with the same fields as specified in the objectDefinition cannot exist.

| spec.evaluationInterval.compliant
| Optional. Used to define how often the policy is evaluated when it is in the compliant state. The values must be in
the format of a duration which is a sequence of numbers with time unit suffixes. For example, `12h30m5s` represents 12
hours, 30 minutes, and 5 seconds. It can also be set to `never` so that the policy is not reevaluated on the compliant
cluster, unless the policy `spec` is updated.

| spec.evaluationInterval.noncompliant
| Optional. Used to define how often the policy is evaluated when it is in the non-compliant state. Similar to the
`evaluationInterval.compliant` parameter, the values must be in the format of a duration which is a sequence of numbers
with time unit suffixes. It can also be set to `never` so that the policy is not reevaluated on the noncompliant
cluster, unless the policy `spec` is updated.
|===

See the policy samples that use https://nvd.nist.gov/800-53/Rev4/control/CA-1[NIST Special Publication 800-53 (Rev. 4)],
and are supported by {product-title-short} from the
https://github.com/stolostron/policy-collection/tree/main/stable/CM-Configuration-Management[`CM-Configuration-Management`
folder]. Learn about how policies are applied on your hub cluster, see
xref:../governance/policy_sample_intro.adoc#supported-policies[Supported policies] for more details. 

Learn how to create and customize policies, see
xref:../governance/manage_policy_overview.adoc#manage-security-policies[Manage security policies]. Refer to
xref:../governance/policy_controllers.adoc#policy-controllers[Policy controllers] for more details about controllers.
